polls/urls.py
from django.conf.urls import url, include
from polls import views
from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns=[
    url(r'^$', views.api_root, name='root'),
    url(r'^polls/$', views.QuestionList.as_view(), name='question-list'),
    url(r'^polls/(?P<pk>[0-9]+)/$', views.QuestionDetail.as_view(), name='question-detail'),
    url(r'^options/$', views.OptionList.as_view(), name='option-list'),
    url(r'^options/(?P<nm>[0-9]+)/$', views.OptionDetail.as_view(), name='option-detail'),
    url(r'^users/$', views.UserList.as_view(), name='user-list'),
    url(r'^users/(?P<pk>[0-9]+)/$', views.UserDetail.as_view(), name='user-detail'),
]

urlpatterns+=[
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

urlpatterns=format_suffix_patterns(urlpatterns)

polly/urls.py
from django.conf.urls import url
from . import views

app_name="polly"

urlpatterns=[
    url(r'^$', views.HomeView.as_view(), name='index'),
    url(r'^myPolls$', views.myPollsView.as_view(), name='mypolls'),
    url(r'^newPoll$', views.create_new_poll, name='newpoll'),
    url(r'^viewPoll/(?P<pk>[0-9]+)$', views.show_and_view_poll, name='vote'),
]

polly/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

polly/forms.py
from django import forms
from django.utils import timezone
from crispy_forms.helper import FormHelper
from crispy_forms.bootstrap import FieldWithButtons, FormActions, StrictButton, Field, InlineRadios
from crispy_forms.layout import Button, Div, Fieldset, Layout, Submit, HTML
from polls.models import Options, Question
from django.contrib.auth.models import User


class OptionForm(forms.models.ModelForm):

    class Meta:
        model=Options
        fields=['option_text']

        labels={
            'option_text': '',
        }

    def __init__(self, *args, **kwargs):
        super(OptionForm, self).__init__(*args, **kwargs)
        self.helper=FormHelper()
        self.helper.layout=Layout(

            Div('option_text', css_class="optionfield col-md-4 col-md-offset-4 col-xs-2 col-xs-offset-4")

        )


class newPollForm(forms.models.ModelForm):
    #option_count=forms.CharField(widget=forms.HiddenInput())

    class Meta:
        model=Question
        fields=['question_text']

        widgets={
            'question_text': forms.fields.TextInput(attrs={
                'placeholder': 'Your question',
                }),
            }
        labels={
            'question_text': ''
        }
        error_messages={
            'question_text': {'required': 'You can not have an empty poll question'}
        }

    def save(self, owner, options):
        data=self.cleaned_data
        time=timezone.now()
        q=Question(question_text=data['question_text'], pub_date=time, owner=owner)
        q.save()
        for i in range(len(options)):
            Options.objects.create(question=q, option_text=options[i]['option_text'], votes=0)
        return q


class viewPollForm(OptionForm):

    option_text=forms.ModelChoiceField(queryset=None, widget=forms.RadioSelect, empty_label=None)

    def __init__(self, *args, **kwargs):
        self.qid=kwargs.pop('q_id')
        super(viewPollForm,self).__init__(*args, **kwargs)
        self.fields['option_text'].queryset=Options.objects.filter(question_id=self.qid)

    def save(self):
        option=self.cleaned_data['option_text']
        option.votes+=1
        option.save()
        return option

class RegisterForm(forms.models.ModelForm):

    class Meta:
        model=User
        fields=['username', 'email', 'password']
        widgets={
            'username': forms.fields.TextInput(attrs={
                'placeholder': 'username',
                }),
            'email': forms.fields.EmailInput(attrs={
                'placeholder': 'email',
                }),
            'password': forms.PasswordInput(attrs={
                'placeholder': 'password',
                }),
            }
        error_messages={
            'username': {'required': "Username is missing", 'unique': "Username already exists."},
            'email': {'required': "Email is missing"},
            'password': {'required': "Password is missing"}
        }

    def clean_email(self):
        email=self.cleaned_data.get('email')
        username=self.cleaned_data.get('username')
        if email and User.objects.filter(email=email).exclude(username=username).count():
            raise forms.ValidationError(u'Email address already exists.')
        return email

polly/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views import generic
from polls.models import Question, Options
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from forms import newPollForm, viewPollForm, OptionForm
from django.forms.formsets import formset_factory
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.
import urllib2, urllib
import simplejson as json


from django.forms.formsets import formset_factory

class HomeView(generic.TemplateView):
    template_name='polly/home.html'

class myPollsView(generic.ListView):
    template_name='polly/myPolls.html'
    context_object_name='poll_list'

    def get_queryset(self):
        return Question.objects.all()


def create_new_poll(request):
    OptionFormSet=formset_factory(OptionForm, extra=2)
    if request.method=='POST':
        form=newPollForm(data=request.POST)
        formset=OptionFormSet(request.POST)
        if form.is_valid() and formset.is_valid():
            options=formset.cleaned_data
            owner=User.objects.get(username='admin')
            form.save(owner=owner, options=options)
        return redirect(reverse('polly:mypolls'))

    else:
        form=newPollForm()
        formset=OptionFormSet()
    return render(request, 'polly/newPoll.html', {'form': form, 'formset': formset})


def show_and_view_poll(request, pk):
    try:
        q=Question.objects.get(id=pk)
    except ObjectDoesNotExist:
        return render(request, 'polly/viewPoll.html', {'error_message': "Poll does not exist!"})

    if request.method=='POST':
        form=viewPollForm(request.POST, q_id=pk)
        if form.is_valid():
            form.save()
            ops=Options.objects.filter(question_id=pk)
            result=json.dumps({'data':[[op.option_text, op.votes] for op in ops]})
            resp=render(request, 'polly/viewPoll.html',{'question': q.question_text, 'result': result})
        #    resp.set_cookie('voted'+pk, True)
    else:
        try:
            voted=request.COOKIES['voted'+pk]
            ops=Options.objects.filter(question_id=pk)
            result=json.dumps({'data':[[op.option_text, op.votes] for op in ops]})
            resp=render(request, 'polly/viewPoll.html',{'question': q.question_text, 'result': result})
        except:
            form=viewPollForm(q_id=pk)
            resp=render(request, 'polly/viewPoll.html',{'question': q.question_text, 'form': form})

    return resp

polly/templates/polly/home.html
{% extends 'polly/layout.html' %}

{% block content %}
<div class="jumbotron">
<h1 class="title">Polly</h1>
<p>Custom polls for all occasions</p>
  {% if name %}
  {% else %}
  <a  class="btn btn-default" href="#signinmodal" data-toggle="modal">Sign up</a>
  {% endif %}
</div>

<div class="container-fluid call">
  <div class="row-fluid">
    <div class="col-md-4">
      <i class="fa fa-edit fa-5x"></i>
      <h2>Create</h2>
      <p>Create your own poll</p>
    </div>
    <div class="col-md-4">
      <i class="fa fa-pie-chart fa-5x"></i>
      <h2>View</h2>
      <p>Download your results or plot them here.</p>
    </div>
    <div class="col-md-4">
      <i class="fa fa-share-alt fa-5x"></i>
      <h2>Share</h2>
      <p>Share your poll via Facebook and invite your friends to vote</p>
    </div>
  </div>
{% endblock %}

polly/templates/polly/layout.html
<!DOCTYPE HTML>
<head>
  <meta charset="utf-8">
  <title>Polly</title>
{%load static%}
<link rel="apple-touch-icon" sizes="180x180" href="{% static 'polly/images/apple-touch-icon.png'%}">
<link rel="icon" type="image/png" href="{% static 'polly/images/favicon-32x32.png' %}" sizes="32x32">
<link rel="icon" type="image/png" href="{% static 'polly/images/favicon-16x16.png'%}" sizes="16x16">
<link rel="manifest" href="{% static 'polly/images/manifest.json' %}">
<link rel="mask-icon" href="{% static 'polly/images//safari-pinned-tab.svg' %}" color="#5bbad5">
<meta name="apple-mobile-web-app-title" content="Polly">
<meta name="application-name" content="Polly">
<meta name="theme-color" content="#ffffff">

<link rel='stylesheet' type='text/css' href="{% static 'polly/polly.css'%}">
<!--<link rel='stylesheet' type='text/css' href='polly/polly.css'>
-->
  <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css'>
  <link rel='stylesheet'  href='https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css'>
  <script src = "https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<!--  <script type="text/javascript" src="/javascripts/layout.js" charset="utf-8"></script>-->
  <script src="//d3js.org/d3.v4.min.js"></script>
</head>
<html>
<body>


  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class='container-fluid'>
        <div class="navbar-header">
          <a class="navbar-brand" href="/"><img src="{% static 'polly/images/bird_16px.png' %}"></img>&nbsp;Polly</a>
        </div>

        <div class="collapse navbar-collapse" id="MyNavBar">
        <ul class="nav navbar-nav navbar-right">
          <li>

              {% if name %}
              <a href="/profile">Hello, {{name}} </a>
              {% else %}
              <a href="#signinmodal" data-toggle="modal">Sign in</a>
              {% endif %}

          </li>
          <li>
            <a href="/newPoll">New poll</a>
          </li>
          <li>
            <a href="/myPolls" >Polls</a>
          </li>
          <li>
            {% if name %}
              <a href="/users/logout">Logout</a>
            {% else %}
            <a href="/about">About</a>
            {% endif %}
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Modal .-->
  <div id="signinmodal" class="modal fade" role=dialog>
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>

        </div>
        <div class="modal-body">
          <div>
            <div role="tabpanel" class="login-tab">
              <!-- Tabs -->
              <ul class="nav nav-tabs">
                <li class="active"><a id="logintaba" href="#logintab" data-toggle="tab">Log in</a></li>
                <li><a id="registertaba" href="#regtab" data-toggle="tab">Register</a></li>
                <li><a id="forgetpasstaba" href="#forgottab" data-toggle="tab">Forgot password</a></li>
              </ul>
              <!-- tab content-->

              <div class="tab-content">
                <div class="tab-pane active" id="logintab">&nbsp;&nbsp;
                  <!--Log in-->
                  <form action="/users/login" method="post" id=login class="thisform">
                    <div class="form-group">
                      <div class="input-group">
                        <div class="input-group-addon"><i class="fa fa-user"></i></div>
                        <input type="text" class="form-control" name="username" placeholder="Username" autocomplete="off"/>
                      </div>
                    </div>
                    <div class="form-group">
                      <div class="input-group">
                        <div class="input-group-addon"><i class="fa fa-lock"></i></div>
                        <input type="password" class="form-control" name="password" placeholder="password"/>
                      </div>
                    </div>
                    <button type="submit" class="btn btn-default" data-loading-text="Signing in..." >Login</button>
                <!--    <p>or</p>


                      <a href="/users/facebook" class="btn btn-primary">Log in with Facebook</a>-->


                    <div class="login-modal-footer">
                      <div class="row">
                        <div class="col-xs-8 col-sm-8 col-md-8">
                          <i class="fa fa-lock"></i>
                          <a href="#" class="forgetpass-tab"> Forgot password? </a>
                        </div>
                        <div class="col-xs-4 col-sm-4 col-md-4">
                          <i class="fa fa-lock"></i>
                          <a href="#" class="signup-tab"> Sign up </a>
                        </div>
                      </div>
                    </div>
                  </form>

                </div>
                <div class="tab-pane" id="regtab">&nbsp;&nbsp;
                  <!--Register-->
                  <form action="/users/register" method="post" id="signup" class="thisform">
                    <div class="form-group">
                      <div class="input-group">
                        <div class="input-group-addon"><i class="fa fa-user"></i></div>
                        <input type="text" class="form-control" name="username" placeholder="username" id="reguser" autocomplete="off"/>
                      </div>
                    </div>
                    <div class="form-group">
                      <div class="input-group">
                        <div class="input-group-addon"><i class="fa fa-at"></i></div>
                        <input type="text" class="form-control" name="email" placeholder="Email" autocomplete="off"/>
                      </div>
                    </div>
                    <div class="form-group">
                      <div class="input-group">
                        <div class="input-group-addon"><i class="fa fa-lock"></i></div>
                        <input type="password" class="form-control" name="password" placeholder="password"/>
                      </div>
                    </div>
                    <button class="btn btn-default" data-loading-text="Registering...">Register</button></br>

                    <div class="alert alert-danger"></div>

                    <div class="login-modal-footer">
                      <div class="row">
                        <div class="col-xs-8 col-sm-8 col-md-8">
                          <i class="fa fa-lock"></i>
                          <a href="#" class="forgetpass-tab">Forgot password?</a>
                        </div>
                        <div class="col-xs-4 col-sm-4 col-md-4">
                          <i class="fa fa-check"></i>
                          <a href="#" class="signin-tab">Sign in</a>
                        </div>
                      </div>
                    </div>
                  </form>
                </div>

                <div class="tab-pane" id="forgottab">&nbsp;&nbsp;
                  <!--Forgot password-->
                  <form >
                    <div class="form-group">
                      <p>Doesn't work yet</p>
                      <div class="input-group">
                        <div class="input-group-addon"><i class="fa fa-at"></i></div>
                        <input type="text" class="form-control" placeholder="Email"/>
                      </div>
                    </div>
                    <button type="button" class="btn btn-default" data-loading-text="Please wait...">Send</button>
                    <div class="login-modal-footer">
                      <div class="row">
                        <div class="col-xs-8 col-sm-8 col-md-8">
                          <i class="fa fa-lock"></i>
                          <a href="#" class="signin-tab">Sign in</a>
                        </div>
                        <div class="col-xs-4 col-sm-4 col-md-4">
                          <i class="fa fa-check"></i>
                          <a href="#" class="signup-tab">Sign up</a>
                        </div>
                      </div>
                    </div>
                  </form>
                </div>

              </div>

            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
<!-- Modal end -->

<div class="jumbotron">
{% block content %}{% endblock %}
</div>


</body>

polly/templates/polly/myPolls.html
{% extends 'polly/layout.html' %}

{% block content %}

<!--{% load static %}
<script type="text/javascript" src="{% static 'polly/javascripts/myPolls.js' %}" charset="utf-8"></script>-->

<h2 class="title">Polls</h2>

<div id="polls" class="container-fluid call">
  {% for poll in poll_list %}
    <a href="{% url 'polly:vote' poll.id%}"><span class="btn btn-default poll-div">{{poll.question_text}}<span></a></br>
  {% endfor %}
</div>
{% if name %}
<a href="newPoll"><div class="btn btn-default newpoll-btn"><i class="fa fa-plus"></i> New poll</div></a>
{% else %}
<div><p>Log in or register to create a new poll</p></div>
{% endif %}
{% endblock %}

polly/templates/polly/newPoll.html
{% extends 'polly/layout.html' %}

{% block content %}

<h1 class="title"> Create poll</h1>

<form action='/newPoll' method="post">
{% csrf_token%}
<!--{% load crispy_forms_tags %}
{% for hidden in form.hidden_fields%}
{{hidden}}
{% endfor%}
{% crispy form %}-->

<p>Question</p>

{{ form |crispy}}
<p>Options</p>
<div class="col-md-4 col-md-offset-4 col-xs-2 col-xs-offset-4">
{{ formset |crispy}}
</div>
<!--<div class="form-group col-md-4 col-md-offset-4 col-xs-2 col-xs-offset-4">
<button class="btn btn-add">More options</button>
</div>-->
<div class="form-group col-md-4 col-md-offset-4 col-xs-2 col-xs-offset-4">
<button class="btn btn-default" type="submit" value="Submit">Submit</button>
</div>
</form>

{%load static%}
<script src="{%static 'polly/javascripts/newPoll.js'%}" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.formset/1.2.2/jquery.formset.min.js"></script>
<script>
  $('.multiField').formset();
</script>
{% endblock %}

polly/templates/polly/viewPoll.html
{% extends 'polly/layout.html' %}

{% block content %}

<h1 class="title">{{question}}</h1>

{% if error_message %}
<div class="has_error">
  {{error_message}}
</div>

{% elif form %}
<form method="post">
  {% csrf_token%}
{% for radio in form.option_text%}
<div class="option">
  {{radio}}
</div>
{%endfor%}
<input type=submit value='Submit' class='btn btn-default'/>
</form>

{% else %}

<div class="resultplot">
</div>
{%load static%}
<script type="text/javascript" src="{% static 'polly/javascripts/plotPollResults.js' %}"></script>
<script type="text/javascript">
var data=JSON.parse('{{result |safe }}');
plotResults(data)
</script>
{% endif %}

{% endblock %}